---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-vsan-penguin-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: vsan
spec:
  storageClassName: vsan
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 15Gi
