# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: penguin-lb
#   labels:
#     run: penguin
# spec:
#   type: LoadBalancer
#   #loadBalancerIP: 192.168.105.79
#   ports:
#   - port: 80
#     name: dynmap
#     protocol: TCP
#     targetPort: 8123
#   - port: 25565
#     name: minecraft
#     protocol: TCP
#     targetPort: 25565
#   - port: 8000
#     name: cloudcmd
#     protocol: TCP
#     targetPort: 8000
#   selector:
#     run: penguin

---
apiVersion: v1
kind: Service
metadata:
  name: penguin-svc
spec:
  type: ClusterIP
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
    name: minecraft
  - port: 80
    protocol: TCP
    targetPort: 8123
    name: http
  - port: 8000
    name: cloudcmd
    protocol: TCP
    targetPort: 8000
  selector:
    run: penguin
