kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: scratch
  name: developer
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: developer-dev-binding
  namespace: scratch
subjects:
- kind: User
  name: dev
  apiGroup: ""
roleRef:
  kind: Role
  name: developer
  apiGroup: ""
