apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: vsan
  selfLink: /apis/storage.k8s.io/v1/storageclasses/vsan
parameters:
  datastore: vsanDatastore
  diskformat: thin
  fstype: ext3
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Retain
volumeBindingMode: Immediate
