apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: vsan
parameters:
  storagepolicyname: "vSAN Default Storage Policy"
  fstype: ext3
provisioner: csi.vsphere.vmware.com
# reclaimPolicy: Delete #Retain
# volumeBindingMode: Immediate
