---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld35
  name: helloworld35
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld35
      name: helloworld35
    spec:
      containers:
      - name: windowswebserver
        imagePullPolicy: IfNotPresent
        image: ragazzilab/dotnet-helloworld:3.5
      imagePullSecrets:
      - name: harbor
      tolerations:
      - key: "windows"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld35
  labels:
    app: helloworld35
spec:
  ports:
  - port: 80
  selector:
    app: helloworld35
  type: NodePort
