# kubectl create secret docker-registry harbor453 --docker-server=harbor.haas-453.pez.pivotal.io --docker-username=admin --docker-password==VMware1! --docker-email=harbor@haas453.pez.pivotal.io

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: dotnet35
  name: dotnet35
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet35
      name: dotnet35
    spec:
      containers:
      - name: windowswebserver
        imagePullPolicy: Always
        image: harbor.haas-453.pez.pivotal.io/windows/aspnet-helloworld:3.5
      imagePullSecrets:
      - name: harbor453
      tolerations:
      - key: "windows"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet35
  labels:
    app: dotnet35
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dotnet35
  type: NodePort
