apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IucGFlLnJhZ2F6emlsYWIuY29tIjp7InVzZXJuYW1lIjoiY29uY291cnNlIiwicGFzc3dvcmQiOiJWTXdhcmUxISIsImVtYWlsIjoiY29uY291cnNlQHJhZ2F6emlsYWIuY29tIiwiYXV0aCI6IlkyOXVZMjkxY25ObE9sWk5kMkZ5WlRFaCJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor
type: kubernetes.io/dockerconfigjson
