apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IucGFlLnJhZ2F6emlsYWIuY29tIjp7InVzZXJuYW1lIjoia3ViZSIsInBhc3N3b3JkIjoiVk13YXJlMSEiLCJlbWFpbCI6Imt1YmVAcmFnYXp6aWxhYi5jb20iLCJhdXRoIjoiYTNWaVpUcFdUWGRoY21VeElRPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor
type: kubernetes.io/dockerconfigjson
