---
apiVersion: v1
data:
  SA_PASSWORD: Vk13YXJlMSE=
kind: Secret
metadata:
  name: mssql
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: sqlwin
  name: sqlwin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlwin
      name: sqlwin
    spec:
      containers:
      - name: windowssqlserver
        imagePullPolicy: IfNotPresent
        image: microsoft/mssql-server-windows-developer:1709
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_IP_ADDRESS
          value: 0.0.0.0
        - name: sa_password
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
      imagePullSecrets:
      - name: harbor
      tolerations:
      - key: "windows"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: sqlwin
spec:
  selector:
    app: sqlwin
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort
