---
apiVersion: v1
kind: Service
metadata:
  name: survive1-lb
  labels:
    run: survive1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: dynmap
    protocol: TCP
    targetPort: 8123
  - port: 25565
    name: minecraft
    protocol: TCP
    targetPort: 25565
  - port: 8000
    name: cloudcmd
    protocol: TCP
    targetPort: 8000
  selector:
    run: survive1

---
apiVersion: v1
kind: Service
metadata:
  name: survive1-svc
spec:
  type: ClusterIP
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
    name: minecraft
  - port: 8123
    protocol: TCP
    targetPort: 8123
    name: dynmap
  selector:
    run: survive1
