apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: survive2
  name: survive2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive2
  strategy: {}
  template:
    metadata:
      labels:
        run: survive2
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: vol-nfs-survive2
        persistentVolumeClaim:
          claimName: vol-nfs-survive2-claim
      - name: vol-backup-survive2
        persistentVolumeClaim:
          claimName: vol-backup-survive2-claim
      containers:
      - image: itzg/minecraft-server
        name: survive2
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        envFrom:
        - configMapRef:
            name: survive2-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-survive2
      - name: cloudcmd
        image: coderaiser/cloudcmd
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-survive2
        ports:
        - containerPort: 8000
          name: cloudcmd
        args:
          - --root
          - /data
          - --name
          - survive
          - --one-file-panel
        securityContext:
          runAsUser: 1000
      - image: itzg/mc-backup:latest
        name: backup
        securityContext:
          runAsUser: 1000
        envFrom:
        - configMapRef:
            name: survive2-config
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-survive2
            readOnly: true
          - mountPath: "/backups"
            name: vol-backup-survive2
