apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
    tier: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis-server
    tier: cache
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-backend
  labels:
    app: fortune-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 9080
  selector:
    app: fortune-backend
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-ui
  labels:
    app: fortune-ui
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fortune-ui
    tier: frontend
---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: fortune-ui
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: fortune-ui
         tier: frontend
     spec:
       containers:
       - name: fortune-ui
         image:  azwickey/fortune-ui:latest
         ports:
         - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
    spec:
      containers:
      - name: redis-server
        image: redis
        ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fortune-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune-backend
        tier: backend
    spec:
      containers:
      - name: yelb-db
        image:  azwickey/fortune-backend-jee:latest
        ports:
        - containerPort: 9080
