---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-vsan-survive5-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: vsan-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
