---
apiVersion: v1
kind: Service
metadata:
  name: bungeecord-lb
  labels:
    run: bungeecord
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    run: bungeecord
