apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: survive4
  name: survive4
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive4
  strategy: {}
  template:
    metadata:
      labels:
        run: survive4
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: vol-nfs-survive4
        persistentVolumeClaim:
          claimName: vol-nfs-survive4-claim
      # - name: vol-backup-survive4
      #   persistentVolumeClaim:
      #     claimName: vol-backup-survive4-claim
      containers:
      - image: itzg/minecraft-server
        name: survive4
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        envFrom:
        - configMapRef:
            name: survive4-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 300
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 300
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-survive4
      - name: cloudcmd
        image: coderaiser/cloudcmd
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-survive4
        ports:
        - containerPort: 8000
          name: cloudcmd
        args:
          - --root
          - /data
          - --name
          - survive
          - --one-file-panel
        securityContext:
          runAsUser: 1000
      # - image: itzg/mc-backup:latest
      #   name: backup
      #   securityContext:
      #     runAsUser: 1000
      #     runAsGroup: 1000
      #   envFrom:
      #   - configMapRef:
      #       name: survive4-config
      #   volumeMounts:
      #     - mountPath: "/data"
      #       name: vol-nfs-survive4
      #       readOnly: true
      #     - mountPath: "/backups"
      #       name: vol-backup-survive4
