apiVersion: v1
data:
  EULA: "true"
  VERSION: 1.15.2 #1.14.4 # 1.12.2
  FORGEVERSION: RECOMMENDED
  TYPE: VANILLA #, FORGE, SPIGOT, PAPER
  SERVER_NAME: "survive2"
  MEMORY: "1G"
  BUILD_FROM_SOURCE: "true" #Spigot
  MOTD: "survive2 - Vanilla on K8s"
  ONLINE_MODE: "false" # false for bungeecord
  SRC_DIR: /data #Backup Source Folder
  BACKUP_INTERVAL: "60"
  BACKUP_NAME: world
  INITIAL_DELAY: "5m" #Delay for Backups
  PRUNE_BACKUP_DAYS: "14"
  RCON_PORT: "25575"
  EXCLUDES: cache,logs,tiles
  BACKUP_METHOD: tar
  DEBUG: "true" #Backup
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: survive2-config
  labels:
    run: survive2
