apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
spec:
  completions: 5
  template:
    spec:
      containers:
      - command: ["/bin/sleep"]
        args: ["3"]
        image: busybox
        name: resting
      restartPolicy: Never
