apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus-local",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prom-np:80",
                "version": 1
            },
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus-games",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://192.168.104.134:80",
                "version": 1
            }
        ]
    }
  influxdb.yaml: |-
   apiVersion: 1
   deleteDatasources:
      - name: Graphite
        orgId: 1
   datasources:
    - name: Influxdb
      type: influxdb
      access: proxy
      orgId: 1
      url: http://influxdb:8086
      password:
      user:
      database: db0
      basicAuth:
      basicAuthUser:
      basicAuthPassword:
      withCredentials:
      isDefault:
      jsonData:
         graphiteVersion: "1.1"
         tlsAuth: false
         tlsAuthWithCACert: false
         httpHeaderName1: "Authorization"
      secureJsonData:
        tlsCACert: "..."
        tlsClientCert: "..."
        tlsClientKey: "..."
        httpHeaderValue1: "Bearer xf5yhfkpsnmgo"
      version: 1
      editable: false
