apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  labels:
    name: teleegrafconf
  namespace: monitoring
data:
  telegraf.conf: |
    [[inputs.vsphere]]
      interval = "300s"

      # update vCenter credential here
      vcenters = [ "https://vcsa.ragazzilab.com/sdk"]
      username = "administrator@vsphere.local"
      password = "VMware1!"

      # provide CA certificate or skip verify
      insecure_skip_verify = true # false
      # ssl_ca = "/path/to/ca"

      # You will need to config the path if your Inventory layout is customized.
      # You can also modify the field if you want to collect a portion of clusters
      # By default, all clusters are collected.

      vsan_cluster_include = ["/*/host/*"]
      vm_metric_include = []
      host_metric_include = []
      cluster_metric_include = []
      datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest"]

      # By default all supported entity will be included
      vsan_metric_skip_verify = true
      vsan_metric_include = [
         "summary.disk-usage",
         "summary.health",
         "summary.resync",
         "performance.cluster-domclient",
         "performance.cluster-domcompmgr",
         "performance.host-domclient",
         "performance.host-domcompmgr",
         "performance.cache-disk",
         "performance.disk-group",
         "performance.capacity-disk",
         "performance.disk-group",
         "performance.virtual-machine",
         "performance.vscsi",
         "performance.virtual-disk",
         "performance.vsan-host-net",
         "performance.vsan-vnic-net",
         "performance.vsan-pnic-net",
         "performance.vsan-iscsi-host",
         "performance.vsan-iscsi-target",
         "performance.vsan-iscsi-lun",
         "performance.lsom-world-cpu",
         "performance.nic-world-cpu",
         "performance.dom-world-cpu",
         "performance.cmmds-world-cpu",
         "performance.host-cpu",
         "performance.host-domowner",
         "performance.host-memory-slab",
         "performance.host-memory-heap"
      ]


      force_discover_on_init = true
      collect_concurrency = 5
      discover_concurrency = 5

    #  ssl_cert = "/path/to/certfile"
    #  ssl_key = "/path/to/keyfile"

    [[outputs.influxdb]]
      ## The full HTTP or UDP URL for your InfluxDB instance.
      ##
      urls = ["http://influxdb:8086"]

      ## The target database for metrics; will be created as needed.
      ## For UDP url endpoint database needs to be configured on server side.
      database = "db0"

      ## The value of this tag will be used to determine the database.  If this
      ## tag is not set the 'database' option is used as the default.
      # database_tag = ""

      ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
      ## Telegraf with a user without permissions to create databases or when the
      ## database already exists.
      skip_database_creation = true

      insecure_skip_verify = true

      flush_interval = "300s"

    [agent]
      debug = true
      quiet = false
