---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: survive1
  name: survive1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive1
  strategy: {}
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: vol-vsan-survive1
      labels:
        run: survive1
    spec:
      volumes:
      - name: vol-vsan-survive1
        persistentVolumeClaim:
          claimName: vol-vsan-survive1-claim
      - name: plugins
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/bukkit-plugins/1.14.4
      - name: source
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/survive
      initContainers:
      - image: itzg/mc-backup
        name: syncdata
        command: ['sh', '-c', 'cp -Rv /backups/* /data/']
        volumeMounts:
          - mountPath: "/data"
            name: vol-vsan-survive1
          - mountPath: "/backups"
            name: source
      containers:
      - image: itzg/minecraft-server
        name: survive1
        envFrom:
        - configMapRef:
            name: survive1-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 300
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 300
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-vsan-survive1
          - mountPath: "/plugins"
            name: plugins
            readOnly: true
      - name: cloudcmd
        image: coderaiser/cloudcmd
        volumeMounts:
          - mountPath: "/data"
            name: vol-vsan-survive1
        ports:
        - containerPort: 8000
          name: cloudcmd
        args:
          - --root
          - /data
          - --name
          - survive
          - --one-file-panel
