---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mssql
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        resources:
          requests:
            memory: "2Gi"
        env:
        - name: MSSQL_PID
          value: "Developer" # "Enterprise, Standard, Express, Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_IP_ADDRESS
          value: 0.0.0.0
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
