kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sample
  annotations:
    volume.beta.kubernetes.io/storage-class: lun01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lub01
