---
apiVersion: v1
data:
  EULA: "true"
  VERSION: LATEST #1.14.4 # 1.12.2
  FORGEVERSION: RECOMMENDED
  TYPE: PAPER # VANILLA, FORGE, SPIGOT, PAPER
  SERVER_NAME: "survive5"
  MEMORY: "2G"
  BUILD_FROM_SOURCE: "false" #Spigot
  MOTD: "survive5 - PaperMC on K8s"
  ONLINE_MODE: "false" # false for bungeecord
kind: ConfigMap
metadata:
  name: survive5-config
  labels:
    run: survive5
