---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: survive5
  name: survive5
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive5
  strategy: {}
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: vol-vsan-survive5
      labels:
        run: survive5
    spec:
      volumes:
      - name: vol-vsan-survive5
        persistentVolumeClaim:
          claimName: vol-vsan-survive5-claim
      - name: plugins
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/bukkit-plugins/1.14.4
      containers:
      - image: itzg/minecraft-server
        name: survive5
        envFrom:
        - configMapRef:
            name: survive5-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-vsan-survive5
          - mountPath: "/plugins"
            name: plugins
            readOnly: true
      - name: cloudcmd
        image: coderaiser/cloudcmd
        volumeMounts:
          - mountPath: "/data"
            name: vol-vsan-survive5
        ports:
        - containerPort: 8000
          name: cloudcmd
        args:
          - --root
          - /data
          - --name
          - survive
          - --one-file-panel
        securityContext:
          runAsUser: 1000
