apiVersion: v1
kind: Service
metadata:
  name: survive5-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.105.77
  ports:
  - port: 80
    name: dynmap
    protocol: TCP
    targetPort: 8123
  - port: 25565
    name: minecraft
    protocol: TCP
    targetPort: 25565
  - port: 8000
    name: cloudcmd
    protocol: TCP
    targetPort: 8000
  selector:
    run: survive4
