---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: survive3
  name: survive3
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive3
  strategy: {}
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: vol-vsan-survive3
        pre.hook.backup.velero.io/command: '["rcon-cli", "save-off"]'
        pre.hook.backup.velero.io/container: survive3
        post.hook.backup.velero.io/command: '["rcon-cli", "save-on"]'
        post.hook.backup.velero.io/container: survive3
      labels:
        run: survive3
    spec:
      volumes:
      - name: vol-vsan-survive3
        persistentVolumeClaim:
          claimName: vol-vsan-survive3-claim
      - name: plugins
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/bukkit-plugins/1.16.1
      # - name: source
      #   nfs:
      #     server: 192.168.96.20
      #     path: /nfs/kubevols/survive3
      # initContainers:
      # - image: itzg/mc-backup
      #   name: syncdata
      #   command: ['sh', '-c', 'cp -Rv /backups/* /data/']
      #   volumeMounts:
      #     - mountPath: "/data"
      #       name: vol-vsan-survive3
      #     - mountPath: "/backups"
      #       name: source
      containers:
      - image: itzg/minecraft-server
        name: survive3
        envFrom:
        - configMapRef:
            name: survive3-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        - containerPort: 80
          name: dynmap
        # readinessProbe:
        #   exec:
        #     command:
        #     - mc-monitor
        #     - status
        #     - localhost
        #   initialDelaySeconds: 300
        #   periodSeconds: 5
        # livenessProbe:
        #   exec:
        #     command:
        #     - mc-monitor
        #     - stats
        #     - localhost
        #   initialDelaySeconds: 300
        #   periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-vsan-survive3
          - mountPath: "/plugins"
            name: plugins
            readOnly: true
      - name: cloudcmd
        image: coderaiser/cloudcmd
        volumeMounts:
          - mountPath: "/data"
            name: vol-vsan-survive3
        ports:
        - containerPort: 8000
          name: cloudcmd
        args:
          - --root
          - /data
          - --name
          - survive
          - --one-file-panel
