apiVersion: v1
kind: Service
metadata:
  name: weatherforecast-service
  namespace: weatherforecast-stage
spec:
  selector:
    app: weatherforecast-api
  ports:
    - port: 8080 
      targetPort: 8080 
  type: LoadBalancer
