apiVersion: v1
kind: Service
metadata:
  name: weatherforecast-service
  namespace: weatherforecast
spec:
  selector:
    app: weatherforecast-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
