---
apiVersion: v1
kind: Service
metadata:
  name: dynmap-surv5
  labels:
    run: survive5
spec:
  type: ClusterIP
  ports:
  - port: 8123
    name: dynmap
    protocol: TCP
    targetPort: 8123
  selector:
    run: survive5
---
apiVersion: v1
kind: Service
metadata:
  name: dynmap-surv4
  labels:
    run: survive4
spec:
  type: ClusterIP
  ports:
  - port: 8123
    name: dynmap
    protocol: TCP
    targetPort: 8123
  selector:
    run: survive4

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dynmap-ing
spec:
  rules:
  - http:
      paths:
      - path: /surv5
        backend:
          serviceName: dynmap-surv5
          servicePort: 8123
      - path: /surv4
        backend:
          serviceName: dynmap-surv4
          servicePort: 8123
