---
apiVersion: v1
data:
  EULA: "true"
  VERSION: LATEST #1.14.4 # 1.12.2
  FORGEVERSION: RECOMMENDED
  TYPE: SPIGOT # VANILLA, FORGE, SPIGOT
  SERVER_NAME: "lobby"
  MEMORY: "1G"
  BUILD_FROM_SOURCE: "true" #Spigot
  MOTD: "lobby - SpigotMC on K8s"
  ONLINE_MODE: "false" # false for bungeecord
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: lobby-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: lobby
  name: lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      run: lobby
  strategy: {}
  template:
    metadata:
      labels:
        run: lobby
    spec:
      volumes:
      - name: vol-nfs-lobby
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/lobby
      containers:
      - image: itzg/minecraft-server
        name: lobby
        envFrom:
        - configMapRef:
            name: lobby-config
        resources:
          requests:
            memory: "1Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-lobby
---
apiVersion: v1
kind: Service
metadata:
  name: lobby-svc
spec:
  type: ClusterIP
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    run: lobby
