---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mctest
  annotations:
    volume.beta.kubernetes.io/storage-class: vsan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: vsan
