---
apiVersion: v1
data:
  EULA: "true"
  VERSION: LATEST #1.14.4 # 1.12.2
  FORGEVERSION: RECOMMENDED
  TYPE: SPIGOT # VANILLA, FORGE, SPIGOT
  SERVER_NAME: "SpigotMC on K8s"
  MEMORY: "1G"
  BUILD_FROM_SOURCE: "true" #Spigot
  MOTD: "SpigotMC on K8s"
  MAX_PLAYERS: "10"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mctest-config
