apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    component: velero
  name: mc1
  namespace: velero
spec:
  accessMode: ReadOnly
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://192.168.100.176:9000
  objectStorage:
    bucket: backup
  provider: aws
