---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv1-daily
spec:
  schedule: '40 0 * * *'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive1
    ttl: 168h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv5-daily
spec:
  schedule: '50 0 * * *'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive5
    ttl: 168h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv4-daily
spec:
  schedule: '45 0 * * *'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive4
    ttl: 168h0m0s
