---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv1-daily
spec:
  schedule: '0 0 * * *'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive1
    ttl: 168h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv2-daily
spec:
  schedule: '0 0 * * *'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive2
    ttl: 168h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv4-daily
spec:
  schedule: '0 0 * * *'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive4
    ttl: 168h0m0s
