---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv1-bihourly
spec:
  schedule: '10 0/2 * * *' #'@every 2h'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive1
    ttl: 24h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv5-bihourly
spec:
  schedule: '20 0/2 * * *' #'@every 2h'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive5
    ttl: 24h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: surv4-bihourly
spec:
  schedule: '30 0/2 * * *' #'@every 2h'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: survive4
    ttl: 24h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: penguin-bihourly
spec:
  schedule: '40 0/2 * * *' #'@every 2h'
  template:
    hooks: {}
    includedNamespaces:
    - mc
    labelSelector:
      matchLabels:
        run: penguin
    ttl: 24h0m0s
