apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"component":"velero"},"name":"restic","namespace":"velero"},"spec":{"selector":{"matchLabels":{"name":"restic"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"component":"velero","name":"restic"}},"spec":{"containers":[{"args":["restic","server"],"command":["/velero"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"VELERO_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"VELERO_SCRATCH_DIR","value":"/scratch"},{"name":"GOOGLE_APPLICATION_CREDENTIALS","value":"/credentials/cloud"},{"name":"AWS_SHARED_CREDENTIALS_FILE","value":"/credentials/cloud"},{"name":"AZURE_CREDENTIALS_FILE","value":"/credentials/cloud"}],"image":"velero/velero:v1.2.0","imagePullPolicy":"IfNotPresent","name":"restic","resources":{},"volumeMounts":[{"mountPath":"/host_pods","mountPropagation":"HostToContainer","name":"host-pods"},{"mountPath":"/scratch","name":"scratch"},{"mountPath":"/credentials","name":"cloud-credentials"}]}],"securityContext":{"runAsUser":0},"serviceAccountName":"velero","volumes":[{"hostPath":{"path":"/var/lib/kubelet/pods"},"name":"host-pods"},{"emptyDir":{},"name":"scratch"},{"name":"cloud-credentials","secret":{"secretName":"cloud-credentials"}}]}},"updateStrategy":{}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: velero
  name: restic
  selfLink: /apis/extensions/v1beta1/namespaces/velero/daemonsets/restic
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: restic
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: velero
        name: restic
    spec:
      containers:
      - args:
        - restic
        - server
        command:
        - /velero
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.2.0
        imagePullPolicy: IfNotPresent
        name: restic
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host_pods
          mountPropagation: HostToContainer
          name: host-pods
        - mountPath: /scratch
          name: scratch
        - mountPath: /credentials
          name: cloud-credentials
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: velero
      serviceAccountName: velero
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/vcap/data/kubelet/pods
          type: ""
        name: host-pods
      - emptyDir: {}
        name: scratch
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: cloud-credentials
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
