---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-vsan-xmage-db
spec:
  storageClassName: vsan
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-vsan-xmage-saved
spec:
  storageClassName: vsan
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 2Gi
