apiVersion: v1
kind: Service
metadata:
  name: xmage-lb
  labels:
    run: xmage
spec:
  type: LoadBalancer
  ports:
  - port: 17171
    name: 17171
    protocol: TCP
    targetPort: 17171
  - port: 17179
    name: 17179
    protocol: TCP
    targetPort: 17179
    run: xmage
