---
apiVersion: v1
data:
  MOTD: "TShock"
kind: ConfigMap
metadata:
  name: tshock-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: tshock
  name: tshock
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tshock
  strategy: {}
  template:
    metadata:
      labels:
        run: tshock
    spec:
      securityContext:
        runAsUser: 501
        runAsGroup: 1000
      volumes:
      - name: vol-nfs-tshock
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/terraria/world
      containers:
      - image: ryshe/terraria:latest
        name: tshock
        args: ["-world /world/world.wld"]
        envFrom:
        - configMapRef:
            name: tshock-config
        resources:
          requests:
            memory: "1Gi"
        ports:
        - containerPort: 7777
          name: main
        volumeMounts:
          - mountPath: "/world"
            name: vol-nfs-tshock
---
apiVersion: v1
kind: Service
metadata:
  name: tshock-lb
spec:
  type: LoadBalancer
  ports:
  - port: 7777
    name: terraria
    protocol: TCP
    targetPort: 7777
  selector:
    run: tshock
