---
apiVersion: pksapi.io/v1beta1
kind: ClusterMetricSink
metadata:
  name: prometheus-sink
spec:
  inputs:
  outputs:
    - type: prometheus_client
      listen: ":9978"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-metric-sink-service
  namespace: pks-system

spec:
  selector:
    app: telegraf
  type: NodePort
  ports:
    - port: 9978
      targetPort: 9978
      nodePort: 31000
