---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pixelmon
  name: pixelmon
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pixelmon
  strategy: {}
  template:
    metadata:
      labels:
        run: pixelmon
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: vol-nfs-pixelmon
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/pixelmon
      containers:
      - image: itzg/minecraft-server
        name: pixelmon
        envFrom:
        - configMapRef:
            name: pixelmon-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-pixelmon
      - name: cloudcmd
        image: coderaiser/cloudcmd
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-pixelmon
        ports:
        - containerPort: 8000
          name: cloudcmd
        args:
          - --root
          - /data
          - --name
          - survive
          - --one-file-panel
