---
apiVersion: v1
data:
  EULA: "true"
  VERSION: 1.12.2 #1.14.4 # 1.12.2
  FORGEVERSION: 14.23.5.2838
  TYPE: FORGE # VANILLA, FORGE, SPIGOT
  SERVER_NAME: "pixelmon"
  MEMORY: "2G"
  BUILD_FROM_SOURCE: "true" #Spigot
  MOTD: "pixelmon - Forge on K8s"
  ONLINE_MODE: "false" # false for bungeecord
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pixelmon-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pixelmon
  name: pixelmon
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pixelmon
  strategy: {}
  template:
    metadata:
      labels:
        run: pixelmon
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: vol-nfs-pixelmon
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/pixelmon
      containers:
      - image: itzg/minecraft-server
        name: pixelmon
        envFrom:
        - configMapRef:
            name: pixelmon-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-pixelmon
---
apiVersion: v1
kind: Service
metadata:
  name: pixelmon-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: dynmap
    protocol: TCP
    targetPort: 8123
  - port: 25565
    name: minecraft
    protocol: TCP
    targetPort: 25565
  selector:
    run: pixelmon
