---
apiVersion: v1
data:
  EULA: "true"
  VERSION: LATEST #1.14.4 # 1.12.2
  FORGEVERSION: RECOMMENDED
  TYPE: SPIGOT # VANILLA, FORGE, SPIGOT
  SERVER_NAME: "survive2"
  MEMORY: "2G"
  BUILD_FROM_SOURCE: "true" #Spigot
  MOTD: "survive2 - SpigotMC on K8s"
  ONLINE_MODE: "false" # false for bungeecord
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: survive2-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: survive2
  name: survive2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive2
  strategy: {}
  template:
    metadata:
      labels:
        run: survive2
    spec:
      volumes:
      - name: vol-nfs-survive2
        nfs:
          server: 192.168.96.20
          path: /nfs/kubevols/survive2
      containers:
      - image: itzg/minecraft-server
        name: survive2
        envFrom:
        - configMapRef:
            name: survive2-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-survive2
---
apiVersion: v1
kind: Service
metadata:
  name: survive2-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: dynmap
    protocol: TCP
    targetPort: 8123
  - port: 25565
    name: minecraft
    protocol: TCP
    targetPort: 25565
  selector:
    run: survive2
