apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: survive
  name: survive
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive
  strategy: {}
  template:
    metadata:
      labels:
        run: survive
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: vol-nfs-survive
        persistentVolumeClaim:
          claimName: vol-nfs-survive-claim
      containers:
      - image: itzg/minecraft-server
        name: survive
        envFrom:
        - configMapRef:
            name: survive-config
        resources:
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 25565
          name: main
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 240
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/data"
            name: vol-nfs-survive
