---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-nfs-minio
  labels:
    type: nfs
    use: minio
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.96.20
    path: /nfs/k8sdynamic #/nfs/minio

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-nfs-minio-claim
spec:
  storageClassName: ""
  selector:
    matchLabels:
      type: nfs
      use: minio
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 500Gi
